name: graphes
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installation de graphviz
      run: sudo apt-get install graphviz -y
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Lancement graphviz
      run: cd TP-Graph; ./run2.sh
    - name: upload du resultat
      uses: actions/upload-artifact@v4
      with:
        name: run2.sh-result
        path: TP-Graph/*.svg
